owner: "Ali"
language: c
target_language: rust
owner: "ctl-project"
name: "ctl"
tag_or_commit_hash: "latest"
repo_url: "https://github.com/example/ctl.git"
original_run_tests_cmd: "cd original-repo/ctl && make test"
migrated_run_tests_cmd: "cd migrated-repo/hello_world && cargo test"
migrated_tests_dir: "migrated-repo/hello_world/tests"
original_project_path: "original-repo/ctl"
migrated_project_path: "migrated-repo/hello_world"
description: "Migration from CTL (C Template Library) to Rust"
migration_date: "2025-07-03"